#!/bin/bash
#version: v1.2.0
#author: zxbetter
#license: MIT
#contact: zhangxinbetter@gmail.com
#site: https://zxbetter.github.io
#time: 2020-08-19 21:06:00
# -----------------------------------------------------------------------------
# 脚本执行逻辑：
#     1. 删除指定的本地分支；
#     2. 删除对应的远程分支。
# ------------------------------------------------------------------------------

set -eo pipefail

SCRIPTPATH=$(
    cd "$(dirname "$0")"
    pwd
)

# 根路径
export APP_HOME="${SCRIPTPATH%/my-tools/*}/my-tools"
# 引入git通用模块
# shellcheck source=/dev/null
. "${APP_HOME}/utils/common"

# 定义函数
# 帮助函数
helpu() {
    cat <<EOF

usage: $0 <option>

删除指定的本地分支和对应的远程分支。

OPTIONS:
  [-b         ] [branchName ...] 指定分支名，多个用空格隔开 
  [--help | -h]                  帮助
EOF

    exit
}

# 解析参数
while true; do
    if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
        helpu
    elif [ "$1" = "-b" ]; then
        shift 1
    else
        break
    fi
done

if [ "X${*}" = "X" ]; then
    helpu
fi

# 执行逻辑

notice_msg "1)删除本地分支 ${*}"
git branch -D "${@}"

notice_msg "2)删除远程分支 ${*}"
git push origin --delete "${@}"

notice_msg "完成!"
