#!/bin/bash
# version: v1.0.2
# author: zxbetter
# license: MIT
# contact: zhangxinbetter@gmail.com
# site: https://zxbetter.github.io
# time: 2020-09-04 18:07:00
# alias: proxy-execute
# ----------------------------------------------------------------------------------------------------------------------
# 使用代理执行命令
# -----------------------------------------------------------------------------------------------------------------------

set -eo pipefail

SCRIPTPATH=$(
    cd "$(dirname "$0")"
    pwd
)

# 根路径
export APP_HOME="${SCRIPTPATH%/my-tools/*}/my-tools"
# 引入通用模块
# shellcheck source=/dev/null
. "${APP_HOME}/utils/common"

# 定义变量
# 代理地址
PROXY_COMMAND="export HTTP_PROXY=http://127.0.0.1:58591; export HTTPS_PROXY=http://127.0.0.1:58591; export ALL_PROXY=socks5://127.0.0.1:51837"

# 定义函数
# 帮助函数
helpu() {
    cat <<EOF

usage: $0 [option] <command>

使用代理执行命令。

OPTIONS:
  [--proxy-command] 指定设置代理的命令
  [--help     | -h] 帮助
EOF

    exit
}

# 解析参数
while true; do
    if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
        helpu
    elif [ "$1" = "--proxy-command" ]; then
        PROXY_COMMAND="${2}"
        shift 2
    else
        break
    fi
done

if [ ${#} -eq 0 ]; then
    helpu
fi

# 执行逻辑

eval "${PROXY_COMMAND}"
notice_msg "代理已启用:"
echo "    HTTP_PROXY=${HTTP_PROXY}"
echo "    HTTPS_PROXY=${HTTPS_PROXY}"
echo "    ALL_PROXY=${ALL_PROXY}"

notice_msg "开始执行命令 "
eval "${@}"
notice_msg "命令执行完成"

unset HTTP_PROXY HTTPS_PROXY ALL_PROXY
notice_msg "代理已关闭..."

notice_msg "完成!"
